### ISSUE TITLE
Cannot create auth.json

### ISSUE THREAD

**Issue by off99555** [determined-ai/determined#2646]
I have error when trying to create a new experiment.
```
(base) C:\Users\off99\Documents\Code\determined-tutorials\fashion_mnist_tf_keras>det experiment create adaptive.yaml .
Traceback (most recent call last):
  File "c:\users\off99\anaconda3\lib\site-packages\determined\cli\cli.py", line 278, in main
    parsed_args.func(parsed_args)
  File "c:\users\off99\anaconda3\lib\site-packages\determined\cli\experiment.py", line 186, in create
    submit_experiment(args)
  File "c:\users\off99\anaconda3\lib\site-packages\determined\common\api\authentication.py", line 379, in f
    cli_auth = Authentication(namespace.master, v.get("user"), try_reauth=True)
  File "c:\users\off99\anaconda3\lib\site-packages\determined\common\api\authentication.py", line 52, in __init__
    self.session = self._init_session(requested_user, password, try_reauth, cert)
  File "c:\users\off99\anaconda3\lib\site-packages\determined\common\api\authentication.py", line 90, in _init_session
    self.token_store.set_token(session_user, token)
  File "c:\users\off99\anaconda3\lib\site-packages\determined\common\api\authentication.py", line 204, in set_token
    tokens[username] = token
  File "c:\users\off99\anaconda3\lib\contextlib.py", line 120, in __exit__
    next(self.gen)
  File "c:\users\off99\anaconda3\lib\site-packages\determined\common\api\authentication.py", line 233, in _persistent_store
    self.temp.rename(self.path)
  File "c:\users\off99\anaconda3\lib\pathlib.py", line 1358, in rename
    self._accessor.rename(self, target)
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'C:\\Users\\off99\\AppData\\Local\\determined\\auth.json.temp' -> 'C:\\Users\\off99\\AppData\\Local\\determined\\auth.json'
```

I think this error happens because I already use another AWS server before, but now I'm changing to use a different server.
I had to delete `auth.json` in order for it to work.

**Update:**
I could reproduce this issue several times. Just do `det deploy aws down` and `det deploy aws up`.

**Comment by off99555** [comment]
![image](https://user-images.githubusercontent.com/15215732/124091288-db4eac00-da7f-11eb-83a0-3b314e7c7ef3.png)
I have another problem this button doesn't do anything in the new version. 0.16.1

**Comment by vishnu2kmohan** [comment]
Thanks for the report @off99555, we'll look into these...
