### ISSUE TITLE
webui test failures in push architecture

### ISSUE THREAD

**Issue by hamidzr** [determined-ai/determined#2750]
- https://app.circleci.com/pipelines/github/determined-ai/determined/14213/workflows/4b822d35-dc2b-40ae-a995-a149bffa67bf/jobs/423269 (3)

Experiment batch operations￼
Modify experiments￼
Check recent tasks

- https://app.circleci.com/pipelines/github/determined-ai/determined/14210/workflows/df40895f-776d-481d-80c4-ac536e03ed92/jobs/423163 (6)

Check recent tasks￼
Experiment batch operations￼
Modify experiments￼
Create tensorboards￼
Filter tasks by type￼
Kill all tasks

circleci insights https://app.circleci.com/insights/github/determined-ai/determined/workflows/test-e2e/tests?branch=push

**Comment by hamidzr** [comment]
check recent tasks failure: it was expecting 7 but got 8 cards
![image](https://user-images.githubusercontent.com/12127420/126381671-59d4c727-ba34-46fb-8a45-217c303e24af.png)

**Comment by hamidzr** [comment]
'can't find an exeriment to kill' 
expected case:
https://user-images.githubusercontent.com/12127420/126382788-3cdeaf83-95b5-4c2a-bb48-8e1620205797.mp4

sometimes pausing takes a while and experiments progress to the completed state

https://user-images.githubusercontent.com/12127420/126382972-bf690a63-6639-4431-9fed-9eed607a3f27.mp4

**Comment by hamidzr** [comment]
`Experiment batch operations` fails because with the previous issue the set up doesn't end up archiving the experiment.

**Comment by hamidzr** [comment]
we probably should use the expect library where we can instead of manual checks and comparisons. one benefit is better logging:

```
 ## Check experiments	 ✔ ✘
        Failed Step: Should have "4" table rows
        Specification: specs/01-setup.spec:12
        Error Message: expect(received).toHaveLength(expected)
        
        Expected length: 4
        Received length: 3
        Received array:  [{"description": "CustomSelector with query tbody tr[data-row-key] ", "objectId": "8721386817028773338.3.164", "runtimeHandler": {"findElements": [Function findElements], "runtimeCallFunctionOn": [Function runtimeCallFunctionOn], "runtimeEvaluate": [Function runtimeEvaluate]}}, {"description": "CustomSelector with query tbody tr[data-row-key] ", "objectId": "8721386817028773338.3.165", "runtimeHandler": {"findElements": [Function findElements], "runtimeCallFunctionOn": [Function runtimeCallFunctionOn], "runtimeEvaluate": [Function runtimeEvaluate]}}, {"description": "CustomSelector with query tbody tr[data-row-key] ", "objectId": "8721386817028773338.3.166", "runtimeHandler": {"findElements": [Function findElements], "runtimeCallFunctionOn": [Function runtimeCallFunctionOn], "runtimeEvaluate": [Function runtimeEvaluate]}}]
        Stacktrace: 
        Error: expect(received).toHaveLength(expected)
        
        Expected length: 4
        Received length: 3
        Received array:  [{"description": "CustomSelector with query tbody tr[data-row-key] ", "objectId": "8721386817028773338.3.164", "runtimeHandler": {"findElements": [Function findElements], "runtimeCallFunctionOn": [Function runtimeCallFunctionOn], "runtimeEvaluate": [Function runtimeEvaluate]}}, {"description": "CustomSelector with query tbody tr[data-row-key] ", "objectId": "8721386817028773338.3.165", "runtimeHandler": {"findElements": [Function findElements], "runtimeCallFunctionOn": [Function runtimeCallFunctionOn], "runtimeEvaluate": [Function runtimeEvaluate]}}, {"description": "CustomSelector with query tbody tr[data-row-key] ", "objectId": "8721386817028773338.3.166", "runtimeHandler": {"findElements": [Function findElements], "runtimeCallFunctionOn": [Function runtimeCallFunctionOn], "runtimeEvaluate": [Function runtimeEvaluate]}}]
            at StepImplementation.<anonymous> (projects/da/determined/webui/tests/tests/StepImplementation.ts:263:18)
            at Generator.next (<anonymous>)
            at fulfilled (projects/da/determined/webui/tests/tests/StepImplementation.ts:14:58)
```


vs 


```
 ## Check experiments	 ✔ ✘
        Failed Step: Should have "4" table rows
        Specification: specs/01-setup.spec:12
        Error Message: waiting failed: retryTimeout 10000ms exceeded
        Stacktrace: 
        Error: waiting failed: retryTimeout 10000ms exceeded
            at waitUntil (/home/hmd/projects/da/determined/webui/tests/node_modules/taiko/lib/helper.js:137:23)
            at Object.waitFor (/home/hmd/projects/da/determined/webui/tests/node_modules/taiko/lib/taiko.js:2361:5)
            at Object.module.exports.<computed> [as waitFor] (/home/hmd/projects/da/determined/webui/tests/node_modules/taiko/lib/taiko.js:2612:14)

```
