### ISSUE TITLE
'TrainerOptimizersMixin' object has no attribute 'lightning_module'

### ISSUE THREAD

**Issue by drozzy** [determined-ai/determined#3526]
I have existing code in pytorch-lightning, and when I try to wrap it with determined, I get this error.
Versions are:
- `pytorch-lightning==1.5.9`
- `determined==0.16.5`

Additionally, it would be nice if determined ignore the `test_step` method in my lightning module, instead of erroring-out.

```
2022-01-30 20:16:30] 0dc91618 || Traceback (most recent call last):
<info> [2022-01-30 20:16:30] 0dc91618 ||   File "/opt/conda/lib/python3.7/runpy.py", line 193, in _run_module_as_main
<info> [2022-01-30 20:16:30] 0dc91618 ||     "__main__", mod_spec)
<info> [2022-01-30 20:16:30] 0dc91618 ||   File "/opt/conda/lib/python3.7/runpy.py", line 85, in _run_code
<info> [2022-01-30 20:16:30] 0dc91618 ||     exec(code, run_globals)
<info> [2022-01-30 20:16:30] 0dc91618 ||   File "/run/determined/pythonuserbase/lib/python3.7/site-packages/determined/exec/harness.py", line 247, in <module>
<info> [2022-01-30 20:16:30] 0dc91618 ||     main()
<info> [2022-01-30 20:16:30] 0dc91618 ||   File "/run/determined/pythonuserbase/lib/python3.7/site-packages/determined/exec/harness.py", line 240, in main
<info> [2022-01-30 20:16:30] 0dc91618 ||     build_and_run_training_pipeline(env)
<info> [2022-01-30 20:16:30] 0dc91618 ||   File "/run/determined/pythonuserbase/lib/python3.7/site-packages/determined/exec/harness.py", line 149, in build_and_run_training_pipeline
<info> [2022-01-30 20:16:30] 0dc91618 ||     hvd_config,
<info> [2022-01-30 20:16:30] 0dc91618 ||   File "/run/determined/pythonuserbase/lib/python3.7/site-packages/determined/load/_trial.py", line 125, in prepare_controller
<info> [2022-01-30 20:16:30] 0dc91618 ||     controller = load_trial(trial_class, env, workloads, load_path, rendezvous_info, hvd_config)
<info> [2022-01-30 20:16:30] 0dc91618 ||   File "/run/determined/pythonuserbase/lib/python3.7/site-packages/determined/load/_trial.py", line 95, in load_trial
<info> [2022-01-30 20:16:30] 0dc91618 ||     trial_inst = trial_class(trial_context)
<info> [2022-01-30 20:16:30] 0dc91618 ||   File "/run/determined/workdir/src/simple_cnn/trial_determined.py", line 25, in __init__
<info> [2022-01-30 20:16:30] 0dc91618 ||     super().__init__(context, lightning_module=lm)
<info> [2022-01-30 20:16:30] 0dc91618 ||   File "/run/determined/pythonuserbase/lib/python3.7/site-packages/determined/pytorch/lightning/_adapter.py", line 185, in __init__
<info> [2022-01-30 20:16:30] 0dc91618 ||     pls.optimizers, pls.lr_schedulers = self.setup_optimizers_schedulers()
<info> [2022-01-30 20:16:30] 0dc91618 ||   File "/run/determined/pythonuserbase/lib/python3.7/site-packages/determined/pytorch/lightning/_adapter.py", line 244, in setup_optimizers_schedulers
<info> [2022-01-30 20:16:30] 0dc91618 ||     self._pls.lm,
<info> [2022-01-30 20:16:30] 0dc91618 ||   File "/run/determined/pythonuserbase/lib/python3.7/site-packages/pytorch_lightning/trainer/optimizers.py", line 33, in init_optimizers
<info> [2022-01-30 20:16:30] 0dc91618 ||     pl_module = self.lightning_module or model
<info> [2022-01-30 20:16:30] 0dc91618 || AttributeError: 'TrainerOptimizersMixin' object has no attribute 'lightning_module'

```

**Comment by drozzy** [comment]
Nevermind, I abandoned the idea of integrating pytorch-lightning.
