### ISSUE TITLE
"ConnectionError: Timed out connecting to master"

### ISSUE THREAD

**Issue by Cccanvas** [determined-ai/determined#3638]
Hi Determined team! I'm installing determined on my local machine using `det deploy local cluster-up`. I get `Waiting for master instance to be available...` before timing out. 
When I run docker ps, I see determined-master and postgres are running, but I cannot connect to localhost:8080. I'm running determined v0.17.9, Docker v19.03.11, and CentOS 7.
Any ideas on how to debug this? Thanks!

Here is the log:
```
$det deploy local cluster-up
WARNING: The DET_DB_PASSWORD variable is not set. Defaulting to a blank string.
WARNING: The DET_VERSION variable is not set. Defaulting to a blank string.
WARNING: The DET_MASTER_CONFIG variable is not set. Defaulting to a blank string.
Stopping determined_determined-master_1 ... done
Stopping determined_determined-db_1     ... done
Removing determined_determined-master_1 ... done
Removing determined_determined-db_1     ... done
Removing network determined_default
WARNING: The DET_DB_PASSWORD variable is not set. Defaulting to a blank string.
WARNING: The DET_VERSION variable is not set. Defaulting to a blank string.
WARNING: The DET_MASTER_CONFIG variable is not set. Defaulting to a blank string.
Removing network determined_default
WARNING: Network determined_default not found.
Creating network "determined_default" with driver "bridge"
Creating determined_determined-db_1 ... done
Creating determined_determined-master_1 ... done
Waiting for master instance to be available...................................
Timed out connecting to master, but attempting to dump logs from cluster...
Attaching to determined_determined-master_1, determined_determined-db_1
determined-db_1      |
determined-db_1      | PostgreSQL Database directory appears to contain a database; Skipping initialization
determined-db_1      |
determined-db_1      | 2022-02-19 15:27:08.779 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
determined-db_1      | 2022-02-19 15:27:08.780 UTC [1] LOG:  could not create IPv6 socket for address "::": Address family not supported by protocol
determined-db_1      | 2022-02-19 15:27:08.780 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
determined-db_1      | 2022-02-19 15:27:08.807 UTC [25] LOG:  database system was shut down at 2022-02-19 15:27:07 UTC
determined-db_1      | 2022-02-19 15:27:08.810 UTC [1] LOG:  database system is ready to accept connections
determined-master_1  | INFO[2022-02-19T15:27:09Z] master configuration: {"config_file":"","log":{"level":"info","color":true},"db":{"user":"postgres","password":"********","migrations":"file:///usr/share/determined/master/static/migrations","host":"determined-db","port":"5432","name":"determined","ssl_mode":"disable","ssl_root_cert":""},"tensorboard_timeout":300,"security":{"default_task":{"id":0,"user_id":0,"user":"root","uid":0,"group":"root","gid":0},"tls":{"cert":"","key":""},"ssh":{"rsa_key_size":1024}},"checkpoint_storage":{"host_path":"/home/****/.local/share/determined","propagation":null,"save_experiment_best":0,"save_trial_best":1,"save_trial_latest":1,"storage_path":null,"type":"shared_fs"},"task_container_defaults":{"shm_size_bytes":4294967296,"network_mode":"bridge","cpu_pod_spec":null,"gpu_pod_spec":null,"add_capabilities":null,"drop_capabilities":null,"devices":null,"bind_mounts":null,"work_dir":null},"port":8080,"harness_path":"/opt/determined","root":"/usr/share/determined/master","telemetry":{"enabled":true,"segment_master_key":"********","segment_webui_key":"********"},"enable_cors":false,"cluster_name":"","logging":{"type":"default"},"hyperparameter_importance":{"workers_limit":2,"queue_limit":16,"cores_per_worker":1,"max_trees":100},"observability":{"enable_prometheus":false},"resource_manager":{"default_aux_resource_pool":"default","default_compute_resource_pool":"default","scheduler":{"fitting_policy":"best","type":"fair_share"},"type":"agent"},"resource_pools":[{"pool_name":"default","description":"","provider":null,"max_aux_containers_per_agent":100,"task_container_defaults":null,"agent_reattach_enabled":false,"agent_reconnect_wait":"25s"}],"__internal":{"audit_logging_enabled":false,"external_sessions":{"login_uri":"","logout_uri":"","jwt_key":""}}}
determined-master_1  | INFO[2022-02-19T15:27:09Z] Determined master 0.17.9 (built with go1.17.7)
determined-master_1  | INFO[2022-02-19T15:27:09Z] connecting to database determined-db:5432
determined-master_1  | INFO[2022-02-19T15:27:09Z] running DB migrations from file:///usr/share/determined/master/static/migrations; this might take a while...
determined-master_1  | INFO[2022-02-19T15:27:09Z] no migrations to apply; version: 20220125131305
determined-master_1  | INFO[2022-02-19T15:27:09Z] DB migrations completed
determined-master_1  | INFO[2022-02-19T15:27:09Z] deleting all snapshots for terminal state experiments
determined-master_1  | INFO[2022-02-19T15:27:09Z] creating resource pool: default               id=agentRM system=master type=agentResourceManager
determined-master_1  | INFO[2022-02-19T15:27:09Z] pool default using global scheduling config   id=agentRM system=master type=agentResourceManager
determined-master_1  | INFO[2022-02-19T15:27:09Z] not enabling provisioner for resource pool: default  id=default resource-pool=default system=master type=ResourcePool
determined-master_1  | INFO[2022-02-19T15:27:09Z] scheduling next resource allocation aggregation in 8h33m51s at 2022-02-20 00:01:00 +0000 UTC  id=allocation-aggregator system=master type=allocationAggregator
determined-master_1  | INFO[2022-02-19T15:27:09Z] telemetry reporting is enabled; run with `--telemetry-enabled=false` to disable
determined-master_1  | INFO[2022-02-19T15:27:09Z] accepting incoming connections on port 8080
Traceback (most recent call last):
  File "/home/****/****/anaconda3/envs/deter/lib/python3.8/site-packages/determined/deploy/local/cluster_utils.py", line 96, in _wait_for_master
    wait_for_master(master_host, master_port, timeout=100)
  File "/home/****/****/anaconda3/envs/deter/lib/python3.8/site-packages/determined/deploy/healthcheck.py", line 26, in wait_for_master
    return wait_for_master_url(master_url, timeout, cert)
  File "/home/****/****/anaconda3/envs/deter/lib/python3.8/site-packages/determined/deploy/healthcheck.py", line 52, in wait_for_master_url
    raise MasterTimeoutExpired
determined.deploy.errors.MasterTimeoutExpired

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/****/****/anaconda3/envs/deter/lib/python3.8/site-packages/determined/cli/cli.py", line 197, in main
    parsed_args.func(parsed_args)
  File "/home/****/****/anaconda3/envs/deter/lib/python3.8/site-packages/determined/deploy/local/cli.py", line 19, in handle_cluster_up
    cluster_utils.cluster_up(
  File "/home/****/****/anaconda3/envs/deter/lib/python3.8/site-packages/determined/deploy/local/cluster_utils.py", line 221, in cluster_up
    master_up(
  File "/home/****/****/anaconda3/envs/deter/lib/python3.8/site-packages/determined/deploy/local/cluster_utils.py", line 196, in master_up
    _wait_for_master("localhost", port, cluster_name)
  File "/home/****/****/anaconda3/envs/deter/lib/python3.8/site-packages/determined/deploy/local/cluster_utils.py", line 101, in _wait_for_master
    raise ConnectionError("Timed out connecting to master")
ConnectionError: Timed out connecting to master
Failed to Create a Determined cluster
```

**Comment by rb-determined-ai** [comment]
Hi @Cccanvas!  Sorry we missed this issue and didn't respond sooner.  We are happy to help you debug here but I can tell you with 100% confidence that we are better at responding to support requests in our slack #support channel.  If you would like to continue there, [here is a link to sign up](https://join.slack.com/t/determined-community/shared_invite/zt-cnj7802v-KcVbaUrIzQOwmkmY7gP0Ew).

**Comment by rb-determined-ai** [comment]
Ok, on this particular issue, I see:
```
accepting incoming connections on port 8080
```
Which means that the master is definitely waiting.

I would guess it's one of:
- a docker configuration problem. You can share the (sanitized) output of `docker inspect determined_master` if you would like.
- an issue with our ip address auto-guessing logic.  You can share the output of `ip route get 8.8.8.8` and we can check on it.
- a firewall problem (you would have to have something very strict).  You can share the (sanitized) `iptables -nvL` and we can check it out, if you feel comfortable with that.

**Comment by rb-determined-ai** [comment]
closing due to inactivity
