### ISSUE TITLE
use Vacode

### ISSUE THREAD

**Issue by heexu976** [determined-ai/determined#3857]

**Comment by heexu976** [comment]
[18:09:50.013] Log Level: 2
[18:09:50.014] remote-ssh@0.78.0
[18:09:50.015] darwin arm64
[18:09:50.018] SSH Resolver called for "ssh-remote+b2191131-08d5-4e00-a3de-7a07e7379c4e", attempt 1
[18:09:50.018] "remote.SSH.useLocalServer": true
[18:09:50.018] "remote.SSH.path": undefined
[18:09:50.019] "remote.SSH.configFile": undefined
[18:09:50.019] "remote.SSH.useFlock": true
[18:09:50.019] "remote.SSH.lockfilesInTmp": false
[18:09:50.019] "remote.SSH.localServerDownload": auto
[18:09:50.019] "remote.SSH.remoteServerListenOnSocket": false
[18:09:50.019] "remote.SSH.showLoginTerminal": false
[18:09:50.020] "remote.SSH.defaultExtensions": []
[18:09:50.020] "remote.SSH.loglevel": 2
[18:09:50.020] "remote.SSH.enableDynamicForwarding": true
[18:09:50.020] "remote.SSH.enableRemoteCommand": false
[18:09:50.020] "remote.SSH.serverPickPortsFromRange": {}
[18:09:50.020] "remote.SSH.serverInstallPath": {}
[18:09:50.029] SSH Resolver called for host: b2191131-08d5-4e00-a3de-7a07e7379c4e
[18:09:50.029] Setting up SSH remote "b2191131-08d5-4e00-a3de-7a07e7379c4e"
[18:09:50.030] Acquiring local install lock: /var/folders/3s/j2wj32d11xl6zjlf9y9s06580000gn/T/vscode-remote-ssh-1259e04e-install.lock
[18:09:50.031] Looking for existing server data file at /Users/hexu/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-1259e04e-e18005f0f1b33c29e81d732535d8c0e47cafb0b5-0.78.0/data.json
[18:09:50.032] Using commit id "e18005f0f1b33c29e81d732535d8c0e47cafb0b5" and quality "stable" for server
[18:09:50.034] Install and start server if needed
[18:09:50.036] PATH: /usr/local/sbin:/usr/local/bin:/Users/hexu/miniforge3/bin:/Users/hexu/miniforge3/condabin:/opt/local/bin:/opt/local/sbin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/Library/Apple/usr/bin
[18:09:50.037] Checking ssh with "ssh -V"
[18:09:50.041] > OpenSSH_8.6p1, LibreSSL 3.3.5

[18:09:50.042] askpass server listening on /var/folders/3s/j2wj32d11xl6zjlf9y9s06580000gn/T/vscode-ssh-askpass-3438334f625d26b273d0e6b35156a174bca0179b.sock
[18:09:50.042] Spawning local server with {"serverId":1,"ipcHandlePath":"/var/folders/3s/j2wj32d11xl6zjlf9y9s06580000gn/T/vscode-ssh-askpass-b1cbff106047c8336fbe8174babe04812c41fd92.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","59304","-o","ConnectTimeout=15","b2191131-08d5-4e00-a3de-7a07e7379c4e"],"serverDataFolderName":".vscode-server","dataFilePath":"/Users/hexu/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-1259e04e-e18005f0f1b33c29e81d732535d8c0e47cafb0b5-0.78.0/data.json"}
[18:09:50.042] Local server env: {"SSH_AUTH_SOCK":"/private/tmp/com.apple.launchd.VJ807ZnaEQ/Listeners","SHELL":"/bin/zsh","DISPLAY":"1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/Users/hexu/.vscode/extensions/ms-vscode-remote.remote-ssh-0.78.0/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/Applications/Visual Studio Code.app/Contents/MacOS/Electron","VSCODE_SSH_ASKPASS_EXTRA_ARGS":"--ms-enable-electron-run-as-node","VSCODE_SSH_ASKPASS_MAIN":"/Users/hexu/.vscode/extensions/ms-vscode-remote.remote-ssh-0.78.0/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/var/folders/3s/j2wj32d11xl6zjlf9y9s06580000gn/T/vscode-ssh-askpass-3438334f625d26b273d0e6b35156a174bca0179b.sock"}
[18:09:50.043] Spawned 6938
[18:09:50.108] > local-server-1> Spawned ssh, pid=6948
[18:09:50.110] stderr> OpenSSH_8.6p1, LibreSSL 3.3.5
[18:09:50.132] stderr> /Applications/Xcode.app/Contents/Developer/usr/bin/python3: Error while finding module specification for 'determined.cli.tunnel' (ModuleNotFoundError: No module named 'determined')
[18:09:50.222] stderr> banner exchange: Connection to UNKNOWN port 65535: Broken pipe
[18:09:50.223] > local-server-1> ssh child died, shutting down
[18:09:50.225] Local server exit: 0
[18:09:50.225] Received install output: local-server-1> Spawned ssh, pid=6948
OpenSSH_8.6p1, LibreSSL 3.3.5
/Applications/Xcode.app/Contents/Developer/usr/bin/python3: Error while finding module specification for 'determined.cli.tunnel' (ModuleNotFoundError: No module named 'determined')
banner exchange: Connection to UNKNOWN port 65535: Broken pipe
local-server-1> ssh child died, shutting down

[18:09:50.226] Failed to parse remote port from server output
[18:09:50.227] Resolver error: Error: 
	at Function.Create (/Users/hexu/.vscode/extensions/ms-vscode-remote.remote-ssh-0.78.0/out/extension.js:1:586041)
	at Object.t.handleInstallOutput (/Users/hexu/.vscode/extensions/ms-vscode-remote.remote-ssh-0.78.0/out/extension.js:1:584693)
	at Object.e [as tryInstallWithLocalServer] (/Users/hexu/.vscode/extensions/ms-vscode-remote.remote-ssh-0.78.0/out/extension.js:1:625125)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async /Users/hexu/.vscode/extensions/ms-vscode-remote.remote-ssh-0.78.0/out/extension.js:1:644162
	at async Object.t.withShowDetailsEvent (/Users/hexu/.vscode/extensions/ms-vscode-remote.remote-ssh-0.78.0/out/extension.js:1:647909)
	at async /Users/hexu/.vscode/extensions/ms-vscode-remote.remote-ssh-0.78.0/out/extension.js:1:623597
	at async b (/Users/hexu/.vscode/extensions/ms-vscode-remote.remote-ssh-0.78.0/out/extension.js:1:620103)
	at async Object.t.resolveWithLocalServer (/Users/hexu/.vscode/extensions/ms-vscode-remote.remote-ssh-0.78.0/out/extension.js:1:623212)
	at async Object.t.resolve (/Users/hexu/.vscode/extensions/ms-vscode-remote.remote-ssh-0.78.0/out/extension.js:1:645519)
	at async /Users/hexu/.vscode/extensions/ms-vscode-remote.remote-ssh-0.78.0/out/extension.js:1:722950
[18:09:50.231] ------

**Comment by mapmeld** [comment]
If you have the error `No module named 'determined'` , did `pip install determined` complete successfully? Are you currently in the virtual environment recommended in the install steps?

Reference: https://github.com/determined-ai/determined#try-out-determined-locally

**Comment by ioga** [comment]
Hello,

>/Applications/Xcode.app/Contents/Developer/usr/bin/python3: Error while finding module specification for 'determined.cli.tunnel' (ModuleNotFoundError: No module named 'determined')

is `/Applications/Xcode.app/Contents/Developer/usr/bin/python3` the python environment you've used to install determined? If not, try switching the python interpreter in VSCode to the correct one.

**Comment by heexu976** [comment]
> 

In fact, determined is deployed in a remote Ubuntu server. I want to use vscode remote SSH to connect to the determined container through my Mac

**Comment by heexu976** [comment]
> If you have the error `No module named 'determined'` , did `pip install determined` complete successfully? Are you currently in the virtual environment recommended in the install steps?
> 
> Reference: https://github.com/determined-ai/determined#try-out-determined-locally

In fact, determined is deployed in a remote Ubuntu server. I want to use vscode remote SSH to connect to the determined container through my Mac

**Comment by heexu976** [comment]
> 



> Hello,
> 
> > /Applications/Xcode.app/Contents/Developer/usr/bin/python3: Error while finding module specification for 'determined.cli.tunnel' (ModuleNotFoundError: No module named 'determined')
> 
> is `/Applications/Xcode.app/Contents/Developer/usr/bin/python3` the python environment you've used to install determined? If not, try switching the python interpreter in VSCode to the correct one.

https://github.com/determined-ai/determined/issues/3857#issuecomment-1088779885

**Comment by heexu976** [comment]
> Hello,
> 
> > /Applications/Xcode.app/Contents/Developer/usr/bin/python3: Error while finding module specification for 'determined.cli.tunnel' (ModuleNotFoundError: No module named 'determined')
> 
> is `/Applications/Xcode.app/Contents/Developer/usr/bin/python3` the python environment you've used to install determined? If not, try switching the python interpreter in VSCode to the correct one.

In fact, determined is deployed in a remote Ubuntu server. I want to use vscode remote SSH to connect to the determined container through my Mac

**Comment by heexu976** [comment]
> If you have the error `No module named 'determined'` , did `pip install determined` complete successfully? Are you currently in the virtual environment recommended in the install steps?
> 
> Reference: https://github.com/determined-ai/determined#try-out-determined-locally

In fact, determined is deployed in a remote Ubuntu server. I want to use vscode remote SSH to connect to the determined container through my Mac

**Comment by ioga** [comment]
> In fact, determined is deployed in a remote Ubuntu server. I want to use vscode remote SSH to connect to the determined container through my Mac

you need to have the determined python package (the client) installed locally to run the tunnel for the remote ssh.
