### ISSUE TITLE
determined.exec.pid_client FAILED

### ISSUE THREAD

**Issue by fengzf-github** [determined-ai/determined#4292]
An error occurs here. An error is reported after the task is executed for the first verification.  After Task is automatically restarted by determined, an error still occurs during the first verification. The task falls into the cycle of error reporting and restart. The following is the task log. I hope developers can pay attention to this issue. Thank you very much！

[2022-06-09T09:22:29.493000Z] 8de2ca81 [rank=1] ||        [3.2050137e+02, 3.6481229e+02, 3.6756943e+02, 3.9728348e+02,
[2022-06-09T09:22:29.493005Z] 8de2ca81 [rank=1] ||         9.7159201e-01],
[2022-06-09T09:22:29.493206Z] 8de2ca81 [rank=1] ||        [3.1654422e+02, 1.4030740e+02, 3.7874539e+02, 1.7714764e+02,
[2022-06-09T09:22:29.493214Z] 8de2ca81 [rank=1] ||         9.5330322e-01],
[2022-06-09T09:22:29.493223Z] 8de2ca81 [rank=1] ||        [3.2699927e+02, 0.0000000e+00, 3.7704303e+02, 2.7200127e+01,
[2022-06-09T09:22:29.493229Z] 8de2ca81 [rank=1] ||         9.2212439e-01],
[2022-06-09T09:22:29.493235Z] 8de2ca81 [rank=1] ||        [3.1836560e+02, 2.1004539e+02, 4.0026996e+02, 2.5591624e+02,
[2022-06-09T09:22:29.493241Z] 8de2ca81 [rank=1] ||         1.4132895e-01],
[2022-06-09T09:22:29.493247Z] 8de2ca81 [rank=1] ||        [3.1884683e+02, 5.5661087e+00, 3.7995108e+02, 1.4293680e+02,
[2022-06-09T09:22:29.493253Z] 8de2ca81 [rank=1] ||         9.3950748e-02],
[2022-06-09T09:22:29.493259Z] 8de2ca81 [rank=1] ||        [3.2015094e+02, 5.9336819e+01, 4.0896088e+02, 1.0419650e+02,
[2022-06-09T09:22:29.493265Z] 8de2ca81 [rank=1] ||         9.1019079e-02],
[2022-06-09T09:22:29.493271Z] 8de2ca81 [rank=1] ||        [3.1327252e+02, 2.8272659e+02, 3.9395959e+02, 3.2715909e+02,
[2022-06-09T09:22:29.493277Z] 8de2ca81 [rank=1] ||         5.9712570e-02]], dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([[3.9041006e+02, 3.6970474e+02, 4.2762350e+02, 3.8189438e+02,
[2022-06-09T09:22:29.493299Z] 8de2ca81 [rank=1] ||         1.2055279e-01]], dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32)], [array([], shape=(0, 5), dtype=float32), array([[4.6614505e+02, 3.6651385e+02, 4.8501767e+02, 3.9500714e+02,
[2022-06-09T09:22:29.493305Z] 8de2ca81 [rank=1] ||         8.8847905e-01],
[2022-06-09T09:22:29.493310Z] 8de2ca81 [rank=1] ||        [4.4631870e+02, 2.5158943e+02, 4.6478696e+02, 2.7949667e+02,
[2022-06-09T09:22:29.493316Z] 8de2ca81 [rank=1] ||         4.5496270e-01],
[2022-06-09T09:22:29.493322Z] 8de2ca81 [rank=1] ||        [4.6399008e+02, 3.6487558e+02, 4.9978189e+02, 3.9833597e+02,
[2022-06-09T09:22:29.493340Z] 8de2ca81 [rank=1] ||         1.2997515e-01]], dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32), array([], shape=(0, 5), dtype=float32)]])])
[2022-06-09T09:22:31.393923Z] 8de2ca81 || ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 36) of binary: /opt/conda/bin/python3
[2022-06-09T09:22:31.401826Z] 8de2ca81 || Traceback (most recent call last):
[2022-06-09T09:22:31.401830Z] 8de2ca81 ||   File "/opt/conda/lib/python3.8/runpy.py", line 194, in _run_module_as_main
[2022-06-09T09:22:31.402034Z] 8de2ca81 ||     return _run_code(code, main_globals, None,
[2022-06-09T09:22:31.402041Z] 8de2ca81 ||   File "/opt/conda/lib/python3.8/runpy.py", line 87, in _run_code
[2022-06-09T09:22:31.402169Z] 8de2ca81 ||     exec(code, run_globals)
[2022-06-09T09:22:31.402172Z] 8de2ca81 ||   File "/opt/conda/lib/python3.8/site-packages/torch/distributed/run.py", line 723, in <module>
[2022-06-09T09:22:31.403006Z] 8de2ca81 ||     main()
[2022-06-09T09:22:31.403010Z] 8de2ca81 ||   File "/opt/conda/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 345, in wrapper
[2022-06-09T09:22:31.403297Z] 8de2ca81 ||     return f(*args, **kwargs)
[2022-06-09T09:22:31.403301Z] 8de2ca81 ||   File "/opt/conda/lib/python3.8/site-packages/torch/distributed/run.py", line 719, in main
[2022-06-09T09:22:31.404102Z] 8de2ca81 ||     run(args)
[2022-06-09T09:22:31.404105Z] 8de2ca81 ||   File "/opt/conda/lib/python3.8/site-packages/torch/distributed/run.py", line 710, in run
[2022-06-09T09:22:31.404845Z] 8de2ca81 ||     elastic_launch(
[2022-06-09T09:22:31.404849Z] 8de2ca81 ||   File "/opt/conda/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
[2022-06-09T09:22:31.404931Z] 8de2ca81 ||     return launch_agent(self._config, self._entrypoint, list(args))
[2022-06-09T09:22:31.404940Z] 8de2ca81 ||   File "/opt/conda/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 259, in launch_agent
[2022-06-09T09:22:31.405171Z] 8de2ca81 ||     raise ChildFailedError(
[2022-06-09T09:22:31.405175Z] 8de2ca81 || torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
[2022-06-09T09:22:31.405176Z] 8de2ca81 || ============================================================
[2022-06-09T09:22:31.405178Z] 8de2ca81 || determined.exec.pid_client FAILED
[2022-06-09T09:22:31.405179Z] 8de2ca81 || ------------------------------------------------------------
[2022-06-09T09:22:31.405181Z] 8de2ca81 || Failures:
[2022-06-09T09:22:31.405182Z] 8de2ca81 || [1]:
[2022-06-09T09:22:31.405183Z] 8de2ca81 ||   time      : 2022-06-09_09:22:31
[2022-06-09T09:22:31.405185Z] 8de2ca81 ||   host      : 5e4bef3a2da3
[2022-06-09T09:22:31.405186Z] 8de2ca81 ||   rank      : 1 (local_rank: 1)
[2022-06-09T09:22:31.405187Z] 8de2ca81 ||   exitcode  : 1 (pid: 37)
[2022-06-09T09:22:31.405189Z] 8de2ca81 ||   error_file: <N/A>
[2022-06-09T09:22:31.405191Z] 8de2ca81 ||   traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2022-06-09T09:22:31.405192Z] 8de2ca81 || ------------------------------------------------------------
[2022-06-09T09:22:31.405193Z] 8de2ca81 || Root Cause (first observed failure):
[2022-06-09T09:22:31.405194Z] 8de2ca81 || [0]:
[2022-06-09T09:22:31.405195Z] 8de2ca81 ||   time      : 2022-06-09_09:22:31
[2022-06-09T09:22:31.405195Z] 8de2ca81 ||   host      : 5e4bef3a2da3
[2022-06-09T09:22:31.405196Z] 8de2ca81 ||   rank      : 0 (local_rank: 0)
[2022-06-09T09:22:31.405197Z] 8de2ca81 ||   exitcode  : 1 (pid: 36)
[2022-06-09T09:22:31.405198Z] 8de2ca81 ||   error_file: <N/A>
[2022-06-09T09:22:31.405200Z] 8de2ca81 ||   traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2022-06-09T09:22:31.405201Z] 8de2ca81 || ============================================================
[2022-06-09T09:22:34.421666Z] 8de2ca81 || + wait_child_exit=1
[2022-06-09T09:22:34.421675Z] 8de2ca81 || + set -e
[2022-06-09T09:22:34.421677Z] 8de2ca81 || + '[' -z '' ']'
[2022-06-09T09:22:34.421680Z] 8de2ca81 || + exit 1
[2022-06-09T09:22:34.421757Z] 8de2ca81 || + source /run/determined/task-logging-teardown.sh
[2022-06-09T09:22:34.421957Z] 8de2ca81 || ++ '[' -n '' ']'
[2022-06-09T09:22:34.772189Z] 8de2ca81 || ERROR: container failed with non-zero exit code: container failed with non-zero exit code: 1 (exit code 1)
[2022-06-09T09:22:34.792319Z] || INFO: Trial (Experiment 137) was terminated: container failed with non-zero exit code: container failed with non-zero exit code: 1 (exit code 1)
[2022-06-09T09:22:34.804061Z] || INFO: Scheduling Trial 131 (Experiment 137) (id: 6929f198-0813-4e4d-ab2b-b46b103eb90d)
[2022-06-09T09:22:34.927262Z] || INFO: Trial 131 (Experiment 137) was assigned to an agent
[2022-06-09T09:22:34.945519Z] 6b88990f || INFO: image already found, skipping pull phase: docker.io/determinedai/model-hub-mmdetection:0.18.1-dev0
[2022-06-09T09:22:35.027787Z] 6b88990f || INFO: copying files to container: /
[2022-06-09T09:22:35.102257Z] 6b88990f || INFO: copying files to container: /run/determined
[2022-06-09T09:22:35.184387Z] 6b88990f || INFO: copying files to container: /
[2022-06-09T09:22:35.275335Z] 6b88990f || INFO: copying files to container: /
[2022-06-09T09:22:35.373648Z] 6b88990f || INFO: copying files to container: /
[2022-06-09T09:22:35.461697Z] 6b88990f || INFO: copying files to container: /
[2022-06-09T09:22:35.540258Z] 6b88990f || INFO: copying files to container: /
[2022-06-09T09:22:36.255426Z] 6b88990f || + STARTUP_HOOK=startup-hook.sh

**Comment by rb-determined-ai** [comment]
Hi @fengzf-github, the pid_client process is a thin wrapper process around your training code.  If you are seeing that it failed, it just means that your training code failed.  Can you share your full experiment config and full trial logs?  What you have shared here doesn't seem to have the real failure in it.

**Comment by fengzf-github** [comment]
The task is indeed executing, but it falls into a cycle from the beginning to the error (determined.exec.pid_client failed). Finally, I killed the task. Then, without changing anything, submit the task again. This time, the task runs successfully until the end.

This is my configuration information：

(1)config.yaml
name: model_hub_mmdet_experiment_test002
defaults:
    - data: disk
    - profiling: disabled
    - searcher: single
    - hyperparameters:
        - base
        - ann_file
checkpoint_storage:
  save_trial_latest: 1
  type: shared_fs
  host_path: /root/.local/share/determined
min_validation_period:
  batches: 505
environment:
  image:
    gpu: determinedai/model-hub-mmdetection:0.18.1-dev0
  environment_variables:
      - OMP_NUM_THREADS=1 # Following pytorch dtrain, this environment variable is set to 1 to avoid overloading the system.
bind_mounts:
   - host_path: /root/mnt/data
     container_path: /run/determined/workdir/data
resources:
  slots_per_trial: 2 # max number of GPUs a trial is allowed to individually use
  shm_size: 200000000000
entrypoint: python3 -m determined.launch.torch_distributed --trial model_hub.mmdetection:MMDetTrial

(2)disk.yaml
file_client_args:
  backend: disk

(3)base.yaml
global_batch_size: 16
config_file: /run/determined/workdir/data/mmconfig/faster_rcnn_r50_fpn_1x_coco.py
merge_config: /mmdetection/configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py
use_pretrained: true
clip_grads: false
# Config for MultiStepLR scheduler
step1: 505 # 8 epochs * 505 batches per epoch
step2: 1515 # 11 epochs * 505 batches per epoch
warmup: 'linear'
warmup_iters: 500
warmup_ratio: 0.001
gamma: 0.1

(4)ann_file.yaml
override_mmdet_config:
  data.train.ann_file:  /run/determined/workdir/data/coco/annotations/instances_train2017.json
  data.val.ann_file: /run/determined/workdir/data/coco/annotations/instances_val2017.json

(5)disabled.yaml
enabled: false

(6)single.yaml
name: single
metric: bbox_mAP
max_length:
  batches: 6080
smaller_is_better: false

(7)/run/determined/workdir/data/mmconfig/faster_rcnn_r50_fpn_1x_coco.py
_base_ = [
    '/mmdetection/configs/_base_/models/faster_rcnn_r50_fpn.py',
    '/mmdetection/configs/_base_/datasets/coco_detection.py',
    '/mmdetection/configs/_base_/schedules/schedule_1x.py',
    '/mmdetection/configs/_base_/default_runtime.py'
]
# model settings
model = dict(roi_head=dict(bbox_head=dict(num_classes=80)))
classes = ("pokong", "duanlu", "duanlu1", "dukong", "quekou", "zhenkong", "cantong")
data = dict(
    samples_per_gpu=8,
    workers_per_gpu=4,
    train=dict(
        classes=classes,
    ),
    val=dict(
        classes=classes,
    ),
    test=dict(
        classes=classes,
    ))
img_norm_cfg = dict(
    mean=[106.705, 113.267, 124.694], std=[76.678, 67.132, 74.083], to_rgb=True)
train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations', with_bbox=True),
    dict(type='Resize', img_scale=(512, 400), keep_ratio=True),
    dict(type='RandomFlip', flip_ratio=0.5),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='Pad', size_divisor=32),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels']),
]
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiScaleFlipAug',
        img_scale=(512, 400),
        flip=False,
        transforms=[
            dict(type='Resize', keep_ratio=True),
            dict(type='RandomFlip'),
            dict(type='Normalize', **img_norm_cfg),
            dict(type='Pad', size_divisor=32),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img']),
        ])
]
log_config = dict(
    interval=1,
    hooks=[
        dict(type='TextLoggerHook'),
        dict(type='TensorboardLoggerHook')
    ])
workflow = [('train', 1), ('val', 1)]
runner = dict(type='EpochBasedRunner', max_epochs=100)
# optimizer
optimizer = dict(type='SGD', lr=0.01, momentum=0.9, weight_decay=0.0001)
evaluation = dict(metric='bbox')

**Comment by rb-determined-ai** [comment]
closing due to inactivity.
