### ISSUE TITLE
When the training task is mount to Minio，How to get data in the model hub task container

### ISSUE THREAD

**Issue by fengzfcany** [determined-ai/determined#4492]
Hello, I have a problem I need your help，thank you！

The following is the content of the configuration file. How to get data in the model hub task container.

# s3.yaml
```
file_client_args:
  backend: s3
  bucket_name: test-data-coco
  access_key: minio
  secret_key: minio@123
  endpoint_url: http://192.168.40.11:9000/
```

# base.yaml

```
global_batch_size: 2
config_file: /mmdetection/configs/cascade_rcnn/cascade_rcnn_r50_fpn_1x_coco.py
#merge_config: /mmdetection/configs/cascade_rcnn/cascade_rcnn_r50_fpn_1x_coco.py

#config_file: /run/determined/workdir/data/mmconfig/faster_rcnn_r50_fpn_1x_coco.py
merge_config: null

use_pretrained: false
clip_grads: false
# Config for MultiStepLR scheduler
step1: 72 # 8 epochs * 9 batches per epoch
step2: 99 # 11 epochs * 9 batches per epoch
warmup: 'linear'
warmup_iters: 12
warmup_ratio: 0.001
gamma: 0.1
```

# ann_file.yaml

```
override_mmdet_config:
  data.train.ann_file:  /run/determined/data/coco/annotations/instances_train2017.json
  data.val.ann_file: /run/determined/data/coco/annotations/instances_val2017.json
```

# config.yaml

```
name: test001
defaults:
    - data: s3
    - profiling: disabled
    - searcher: single
    - hyperparameters:
        - base
        - ann_file

checkpoint_storage:
  save_trial_latest: 1
  type: s3
  bucket: test-result-coco
  access_key: minio
  secret_key: minio@123
  endpoint_url: http://192.168.40.11:9001/
  prefix: /output

min_validation_period:
  batches: 72

environment:
  image:
    gpu: determinedai/model-hub-mmdetection:0.18.1-dev0
  environment_variables:
      - OMP_NUM_THREADS=1 # Following pytorch dtrain, this environment variable is set to 1 to avoid overloading the system.

resources:
  slots_per_trial: 2 # max number of GPUs a trial is allowed to individually use
  shm_size: 200000000000
entrypoint: python3 -m determined.launch.torch_distributed --trial model_hub.mmdetection:MMDetTrial



```
#  minio bucket test-data-coco contain coco dataset

```
The format of data directory in the bucket is：
        /data/coco
                 annotations
                 test2017
                 train2017
                 val2017

```

# task log error

```
[2022-07-07T14:05:58.988478Z] 84131b79 [rank=1] || INFO: [44] root: Creating PyTorchTrialController with MMDetTrial.
[2022-07-07T14:05:59.405286Z] 540b596e [rank=0] || INFO: [45] root: Creating PyTorchTrialController with MMDetTrial.
[2022-07-07T14:05:59.405291Z] 540b596e [rank=0] || INFO: [45] root: Adding lr updater callback.
[2022-07-07T14:05:59.414101Z] 540b596e [rank=0] || ERROR: [45] root: Could not download missing annotation file.  Encountered __init__() got an unexpected keyword argument 'access_key'.Please make sure it is available at the following path /run/determined/data/coco/annotations/instances_train2017.json.
[2022-07-07T14:05:59.414107Z] 540b596e [rank=0] || loading annotations into memory...
[2022-07-07T14:05:59.414184Z] 540b596e [rank=0] || Traceback (most recent call last):
[2022-07-07T14:05:59.414186Z] 540b596e [rank=0] ||   File "/mmcv/mmcv/utils/registry.py", line 69, in build_from_cfg
[2022-07-07T14:05:59.414815Z] 540b596e [rank=0] ||     return obj_cls(**args)
[2022-07-07T14:05:59.414818Z] 540b596e [rank=0] ||   File "/mmdetection/mmdet/datasets/custom.py", line 95, in __init__
[2022-07-07T14:05:59.414819Z] 540b596e [rank=0] ||     self.data_infos = self.load_annotations(local_path)
[2022-07-07T14:05:59.414819Z] 540b596e [rank=0] ||   File "/mmdetection/mmdet/datasets/coco.py", line 72, in load_annotations
[2022-07-07T14:05:59.414820Z] 540b596e [rank=0] ||     self.coco = COCO(ann_file)
[2022-07-07T14:05:59.414821Z] 540b596e [rank=0] ||   File "/mmdetection/mmdet/datasets/api_wrappers/coco_api.py", line 23, in __init__
[2022-07-07T14:05:59.414821Z] 540b596e [rank=0] ||     super().__init__(annotation_file=annotation_file)
[2022-07-07T14:05:59.414822Z] 540b596e [rank=0] ||   File "/opt/conda/lib/python3.8/site-packages/pycocotools/coco.py", line 81, in __init__
[2022-07-07T14:05:59.414822Z] 540b596e [rank=0] ||     with open(annotation_file, 'r') as f:
[2022-07-07T14:05:59.414823Z] 540b596e [rank=0] || FileNotFoundError: [Errno 2] No such file or directory: '/run/determined/data/coco/annotations/instances_train2017.json'
[2022-07-07T14:05:59.414824Z] 540b596e [rank=0] || 
[2022-07-07T14:05:59.414824Z] 540b596e [rank=0] || During handling of the above exception, another exception occurred:
[2022-07-07T14:05:59.414825Z] 540b596e [rank=0] || 
[2022-07-07T14:05:59.414825Z] 540b596e [rank=0] || Traceback (most recent call last):
[2022-07-07T14:05:59.414826Z] 540b596e [rank=0] ||   File "/opt/conda/lib/python3.8/runpy.py", line 194, in _run_module_as_main
[2022-07-07T14:05:59.416025Z] 540b596e [rank=0] ||     return _run_code(code, main_globals, None,
[2022-07-07T14:05:59.416028Z] 540b596e [rank=0] ||   File "/opt/conda/lib/python3.8/runpy.py", line 87, in _run_code
[2022-07-07T14:05:59.416028Z] 540b596e [rank=0] ||     exec(code, run_globals)
[2022-07-07T14:05:59.416029Z] 540b596e [rank=0] ||   File "/run/determined/pythonuserbase/lib/python3.8/site-packages/determined/exec/harness.py", line 130, in <module>
[2022-07-07T14:05:59.416029Z] 540b596e [rank=0] ||     sys.exit(main(args.train_entrypoint))
[2022-07-07T14:05:59.416029Z] 540b596e [rank=0] ||   File "/run/determined/pythonuserbase/lib/python3.8/site-packages/determined/exec/harness.py", line 121, in main
[2022-07-07T14:05:59.416030Z] 540b596e [rank=0] ||     controller.run()
[2022-07-07T14:05:59.416031Z] 540b596e [rank=0] ||   File "/run/determined/pythonuserbase/lib/python3.8/site-packages/determined/pytorch/_pytorch_trial.py", line 216, in run
[2022-07-07T14:05:59.416031Z] 540b596e [rank=0] ||     self._set_data_loaders()
[2022-07-07T14:05:59.416032Z] 540b596e [rank=0] ||   File "/run/determined/pythonuserbase/lib/python3.8/site-packages/determined/pytorch/_pytorch_trial.py", line 143, in _set_data_loaders
[2022-07-07T14:05:59.416033Z] 540b596e [rank=0] ||     train_data = self.trial.build_training_data_loader()
[2022-07-07T14:05:59.416033Z] 540b596e [rank=0] ||   File "/opt/conda/lib/python3.8/site-packages/model_hub-0.18.3.dev0-py3.8.egg/model_hub/mmdetection/_trial.py", line 202, in build_training_data_loader
[2022-07-07T14:05:59.416034Z] 540b596e [rank=0] ||     dataset, dataloader = data.build_dataloader(
[2022-07-07T14:05:59.416035Z] 540b596e [rank=0] ||   File "/opt/conda/lib/python3.8/site-packages/model_hub-0.18.3.dev0-py3.8.egg/model_hub/mmdetection/_data.py", line 180, in build_dataloader
[2022-07-07T14:05:59.416035Z] 540b596e [rank=0] ||     dataset = mmdet.datasets.build_dataset(cfg, {"test_mode": test_mode})
[2022-07-07T14:05:59.416036Z] 540b596e [rank=0] ||   File "/mmdetection/mmdet/datasets/builder.py", line 82, in build_dataset
[2022-07-07T14:05:59.416037Z] 540b596e [rank=0] ||     dataset = build_from_cfg(cfg, DATASETS, default_args)
[2022-07-07T14:05:59.416037Z] 540b596e [rank=0] ||   File "/mmcv/mmcv/utils/registry.py", line 72, in build_from_cfg
[2022-07-07T14:05:59.416038Z] 540b596e [rank=0] ||     raise type(e)(f'{obj_cls.__name__}: {e}')
[2022-07-07T14:05:59.416038Z] 540b596e [rank=0] || FileNotFoundError: CocoDataset: [Errno 2] No such file or directory: '/run/determined/data/coco/annotations/instances_train2017.json'
[2022-07-07T14:05:58.994288Z] 84131b79 [rank=1] || ERROR: [44] root: Could not download missing annotation file.  Encountered __init__() got an unexpected keyword argument 'access_key'.Please make sure it is available at the following path /run/determined/data/coco/annotations/instances_train2017.json.
[2022-07-07T14:05:58.994876Z] 84131b79 [rank=1] || loading annotations into memory...
[2022-07-07T14:05:58.995125Z] 84131b79 [rank=1] || Traceback (most recent call last):
[2022-07-07T14:05:58.995127Z] 84131b79 [rank=1] ||   File "/mmcv/mmcv/utils/registry.py", line 69, in build_from_cfg
[2022-07-07T14:05:58.995467Z] 84131b79 [rank=1] ||     return obj_cls(**args)
[2022-07-07T14:05:58.995469Z] 84131b79 [rank=1] ||   File "/mmdetection/mmdet/datasets/custom.py", line 95, in __init__
[2022-07-07T14:05:58.995812Z] 84131b79 [rank=1] ||     self.data_infos = self.load_annotations(local_path)
[2022-07-07T14:05:58.995814Z] 84131b79 [rank=1] ||   File "/mmdetection/mmdet/datasets/coco.py", line 72, in load_annotations
[2022-07-07T14:05:58.996132Z] 84131b79 [rank=1] ||     self.coco = COCO(ann_file)
[2022-07-07T14:05:58.996134Z] 84131b79 [rank=1] ||   File "/mmdetection/mmdet/datasets/api_wrappers/coco_api.py", line 23, in __init__
[2022-07-07T14:05:58.996498Z] 84131b79 [rank=1] ||     super().__init__(annotation_file=annotation_file)
[2022-07-07T14:05:58.996499Z] 84131b79 [rank=1] ||   File "/opt/conda/lib/python3.8/site-packages/pycocotools/coco.py", line 81, in __init__
[2022-07-07T14:05:58.996818Z] 84131b79 [rank=1] ||     with open(annotation_file, 'r') as f:
[2022-07-07T14:05:58.996820Z] 84131b79 [rank=1] || FileNotFoundError: [Errno 2] No such file or directory: '/run/determined/data/coco/annotations/instances_train2017.json'
[2022-07-07T14:05:58.996821Z] 84131b79 [rank=1] || 
[2022-07-07T14:05:58.996821Z] 84131b79 [rank=1] || During handling of the above exception, another exception occurred:
[2022-07-07T14:05:58.996822Z] 84131b79 [rank=1] || 
[2022-07-07T14:05:58.996823Z] 84131b79 [rank=1] || Traceback (most recent call last):
[2022-07-07T14:05:58.996825Z] 84131b79 [rank=1] ||   File "/opt/conda/lib/python3.8/runpy.py", line 194, in _run_module_as_main
[2022-07-07T14:05:58.997620Z] 84131b79 [rank=1] ||     return _run_code(code, main_globals, None,
[2022-07-07T14:05:58.997624Z] 84131b79 [rank=1] ||   File "/opt/conda/lib/python3.8/runpy.py", line 87, in _run_code
[2022-07-07T14:05:58.997624Z] 84131b79 [rank=1] ||     exec(code, run_globals)
[2022-07-07T14:05:58.997625Z] 84131b79 [rank=1] ||   File "/run/determined/pythonuserbase/lib/python3.8/site-packages/determined/exec/harness.py", line 130, in <module>
[2022-07-07T14:05:58.997837Z] 84131b79 [rank=1] ||     sys.exit(main(args.train_entrypoint))
[2022-07-07T14:05:58.997838Z] 84131b79 [rank=1] ||   File "/run/determined/pythonuserbase/lib/python3.8/site-packages/determined/exec/harness.py", line 121, in main
[2022-07-07T14:05:58.997839Z] 84131b79 [rank=1] ||     controller.run()
[2022-07-07T14:05:58.997839Z] 84131b79 [rank=1] ||   File "/run/determined/pythonuserbase/lib/python3.8/site-packages/determined/pytorch/_pytorch_trial.py", line 216, in run
[2022-07-07T14:05:58.998581Z] 84131b79 [rank=1] ||     self._set_data_loaders()
[2022-07-07T14:05:58.998669Z] 84131b79 [rank=1] ||   File "/run/determined/pythonuserbase/lib/python3.8/site-packages/determined/pytorch/_pytorch_trial.py", line 143, in _set_data_loaders
[2022-07-07T14:05:58.998671Z] 84131b79 [rank=1] ||     train_data = self.trial.build_training_data_loader()
[2022-07-07T14:05:58.998671Z] 84131b79 [rank=1] ||   File "/opt/conda/lib/python3.8/site-packages/model_hub-0.18.3.dev0-py3.8.egg/model_hub/mmdetection/_trial.py", line 202, in build_training_data_loader
[2022-07-07T14:05:58.999138Z] 84131b79 [rank=1] ||     dataset, dataloader = data.build_dataloader(
[2022-07-07T14:05:58.999139Z] 84131b79 [rank=1] ||   File "/opt/conda/lib/python3.8/site-packages/model_hub-0.18.3.dev0-py3.8.egg/model_hub/mmdetection/_data.py", line 180, in build_dataloader
[2022-07-07T14:05:58.999444Z] 84131b79 [rank=1] ||     dataset = mmdet.datasets.build_dataset(cfg, {"test_mode": test_mode})
[2022-07-07T14:05:58.999445Z] 84131b79 [rank=1] ||   File "/mmdetection/mmdet/datasets/builder.py", line 82, in build_dataset
[2022-07-07T14:05:59.004011Z] 84131b79 [rank=1] ||     dataset = build_from_cfg(cfg, DATASETS, default_args)
[2022-07-07T14:05:59.004016Z] 84131b79 [rank=1] ||   File "/mmcv/mmcv/utils/registry.py", line 72, in build_from_cfg
[2022-07-07T14:05:59.004017Z] 84131b79 [rank=1] ||     raise type(e)(f'{obj_cls.__name__}: {e}')
[2022-07-07T14:05:59.004018Z] 84131b79 [rank=1] || FileNotFoundError: CocoDataset: [Errno 2] No such file or directory: '/run/determined/data/coco/annotations/instances_train2017.json'
[2022-07-07T14:06:04.692213Z] 540b596e || WARNING:torch.distributed.elastic.agent.server.api:Received 15 death signal, shutting down workers
[2022-07-07T14:06:04.695365Z] 540b596e || Traceback (most recent call last):
[2022-07-07T14:06:04.695370Z] 540b596e ||   File "/opt/conda/lib/python3.8/runpy.py", line 194, in _run_module_as_main
[2022-07-07T14:06:04.695563Z] 540b596e ||     return _run_code(code, main_globals, None,
[2022-07-07T14:06:04.695565Z] 540b596e ||   File "/opt/conda/lib/python3.8/runpy.py", line 87, in _run_code
[2022-07-07T14:06:04.695565Z] 540b596e ||     exec(code, run_globals)
[2022-07-07T14:06:04.695566Z] 540b596e ||   File "/opt/conda/lib/python3.8/site-packages/torch/distributed/run.py", line 765, in <module>
[2022-07-07T14:06:04.696093Z] 540b596e ||     main()
[2022-07-07T14:06:04.696095Z] 540b596e ||   File "/opt/conda/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 345, in wrapper
[2022-07-07T14:06:04.696220Z] 540b596e ||     return f(*args, **kwargs)
[2022-07-07T14:06:04.696222Z] 540b596e ||   File "/opt/conda/lib/python3.8/site-packages/torch/distributed/run.py", line 761, in main
[2022-07-07T14:06:04.696606Z] 540b596e ||     run(args)
[2022-07-07T14:06:04.696608Z] 540b596e ||   File "/opt/conda/lib/python3.8/site-packages/torch/distributed/run.py", line 752, in run
[2022-07-07T14:06:04.697080Z] 540b596e ||     elastic_launch(
[2022-07-07T14:06:04.697082Z] 540b596e ||   File "/opt/conda/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
[2022-07-07T14:06:04.697199Z] 540b596e ||     return launch_agent(self._config, self._entrypoint, list(args))
[2022-07-07T14:06:04.697201Z] 540b596e ||   File "/opt/conda/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 236, in launch_agent
[2022-07-07T14:06:04.697327Z] 540b596e ||     result = agent.run()
[2022-07-07T14:06:04.697328Z] 540b596e ||   File "/opt/conda/lib/python3.8/site-packages/torch/distributed/elastic/metrics/api.py", line 125, in wrapper
[2022-07-07T14:06:04.697416Z] 540b596e ||     result = f(*args, **kwargs)
[2022-07-07T14:06:04.697417Z] 540b596e ||   File "/opt/conda/lib/python3.8/site-packages/torch/distributed/elastic/agent/server/api.py", line 709, in run
[2022-07-07T14:06:04.697701Z] 540b596e ||     result = self._invoke_run(role)
[2022-07-07T14:06:04.697703Z] 540b596e ||   File "/opt/conda/lib/python3.8/site-packages/torch/distributed/elastic/agent/server/api.py", line 850, in _invoke_run
[2022-07-07T14:06:04.697797Z] 540b596e ||     time.sleep(monitor_interval)
[2022-07-07T14:06:04.697798Z] 540b596e ||   File "/opt/conda/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/api.py", line 60, in _terminate_process_handler
[2022-07-07T14:06:04.697861Z] 540b596e ||     raise SignalException(f"Process {os.getpid()} got signal: {sigval}", sigval=sigval)
[2022-07-07T14:06:04.697862Z] 540b596e || torch.distributed.elastic.multiprocessing.api.SignalException: Process 37 got signal: 15
[2022-07-07T14:06:04.414394Z] 84131b79 || WARNING:torch.distributed.elastic.agent.server.api:Received 15 death signal, shutting down workers
[2022-07-07T14:06:04.422927Z] 84131b79 || Traceback (most recent call last):
[2022-07-07T14:06:04.422931Z] 84131b79 ||   File "/opt/conda/lib/python3.8/runpy.py", line 194, in _run_module_as_main
[2022-07-07T14:06:04.422932Z] 84131b79 ||     return _run_code(code, main_globals, None,
[2022-07-07T14:06:04.422933Z] 84131b79 ||   File "/opt/conda/lib/python3.8/runpy.py", line 87, in _run_code
[2022-07-07T14:06:04.422934Z] 84131b79 ||     exec(code, run_globals)
[2022-07-07T14:06:04.422934Z] 84131b79 ||   File "/opt/conda/lib/python3.8/site-packages/torch/distributed/run.py", line 765, in <module>
[2022-07-07T14:06:04.425627Z] 84131b79 ||     main()
[2022-07-07T14:06:04.425630Z] 84131b79 ||   File "/opt/conda/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 345, in wrapper
[2022-07-07T14:06:04.425631Z] 84131b79 ||     return f(*args, **kwargs)
[2022-07-07T14:06:04.425632Z] 84131b79 ||   File "/opt/conda/lib/python3.8/site-packages/torch/distributed/run.py", line 761, in main
[2022-07-07T14:06:04.425632Z] 84131b79 ||     run(args)
[2022-07-07T14:06:04.425633Z] 84131b79 ||   File "/opt/conda/lib/python3.8/site-packages/torch/distributed/run.py", line 752, in run
[2022-07-07T14:06:04.425633Z] 84131b79 ||     elastic_launch(
[2022-07-07T14:06:04.425676Z] 84131b79 ||   File "/opt/conda/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
[2022-07-07T14:06:04.425677Z] 84131b79 ||     return launch_agent(self._config, self._entrypoint, list(args))
[2022-07-07T14:06:04.425678Z] 84131b79 ||   File "/opt/conda/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 236, in launch_agent
[2022-07-07T14:06:04.425679Z] 84131b79 ||     result = agent.run()
[2022-07-07T14:06:04.425679Z] 84131b79 ||   File "/opt/conda/lib/python3.8/site-packages/torch/distributed/elastic/metrics/api.py", line 125, in wrapper
[2022-07-07T14:06:04.425680Z] 84131b79 ||     result = f(*args, **kwargs)
[2022-07-07T14:06:04.425681Z] 84131b79 ||   File "/opt/conda/lib/python3.8/site-packages/torch/distributed/elastic/agent/server/api.py", line 709, in run
[2022-07-07T14:06:04.427340Z] 84131b79 ||     result = self._invoke_run(role)
[2022-07-07T14:06:04.427342Z] 84131b79 ||   File "/opt/conda/lib/python3.8/site-packages/torch/distributed/elastic/agent/server/api.py", line 850, in _invoke_run
[2022-07-07T14:06:04.427343Z] 84131b79 ||     time.sleep(monitor_interval)
[2022-07-07T14:06:04.427344Z] 84131b79 ||   File "/opt/conda/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/api.py", line 60, in _terminate_process_handler
[2022-07-07T14:06:04.432443Z] 84131b79 ||     raise SignalException(f"Process {os.getpid()} got signal: {sigval}", sigval=sigval)
[2022-07-07T14:06:04.432446Z] 84131b79 || torch.distributed.elastic.multiprocessing.api.SignalException: Process 37 got signal: 15
[2022-07-07T14:06:05.153664Z] 540b596e || + wait_child_exit=1
[2022-07-07T14:06:05.153668Z] 540b596e || + set -e
[2022-07-07T14:06:05.153668Z] 540b596e || + '[' -z '' ']'
[2022-07-07T14:06:05.153669Z] 540b596e || + exit 1
[2022-07-07T14:06:05.153670Z] 540b596e || + source /run/determined/task-logging-teardown.sh
[2022-07-07T14:06:05.153753Z] 540b596e || ++ '[' -n '' ']'
[2022-07-07T14:06:05.255809Z] 540b596e || ERROR: container failed with non-zero exit code: container failed with non-zero exit code: 1 (exit code 1)
[2022-07-07T14:06:05.517142Z] 84131b79 || ERROR: container failed with non-zero exit code: container failed with non-zero exit code: 137 (exit code 137)
[2022-07-07T14:06:05.522088Z] || INFO: Trial 24 (Experiment 26) was terminated: container failed with non-zero exit code: container failed with non-zero exit code: 1 (exit code 1)
 
```

**Comment by rb-determined-ai** [comment]
Minio is not a filesystem, it's a key-value store.  You can't "mount" minio into your container, you have to download from minio to your container.  Use the minio library to do it.  Those docs are [here](https://docs.min.io/docs/golang-client-api-reference.html).

Also, don't put anything in `/run/determined`.  You can break your training containers that way.

**Comment by fengzf-github** [comment]
In other words, the code of pulling data from Minio in the training task container needs to be implemented by ourselves, right?

**Comment by fengzf-github** [comment]
A task is trained by two agents at the same time. What is the relationship between the tasks in the two agents? Which agent is the result of the last output model?

**Comment by fengzf-github** [comment]
ok，thank you！

**Comment by fengzf-github** [comment]
Tasks are submitted in the mode of Hydra in the model hub.

**Comment by rb-determined-ai** [comment]
do you have any more questions about this?

**Comment by rb-determined-ai** [comment]
I don't see how hydra is relevant.  Hydra is a configuration framework, but you still need to download data from minio to train on it.

**Comment by rb-determined-ai** [comment]
great!
