### ISSUE TITLE
[bug]  Can not use vscode ssh

### ISSUE THREAD

**Issue by heexu976** [determined-ai/determined#4785]
### Describe the bug

1

### Reproduction Steps

1.
2.
3.

### Expected Behavior

1

### Screenshot

[13:49:30.432] Log Level: 2
[13:49:30.433] remote-ssh@0.84.0
[13:49:30.433] darwin arm64
[13:49:30.436] SSH Resolver called for "ssh-remote+1b9ada82-8da0-4f32-bf7c-52fdee8c6198", attempt 1
[13:49:30.436] "remote.SSH.useLocalServer": false
[13:49:30.436] "remote.SSH.showLoginTerminal": false
[13:49:30.436] "remote.SSH.remotePlatform": {"81":"linux","172.22.105.37":"linux"}
[13:49:30.436] "remote.SSH.path": undefined
[13:49:30.437] "remote.SSH.configFile": undefined
[13:49:30.437] "remote.SSH.useFlock": true
[13:49:30.437] "remote.SSH.lockfilesInTmp": false
[13:49:30.437] "remote.SSH.localServerDownload": auto
[13:49:30.438] "remote.SSH.remoteServerListenOnSocket": false
[13:49:30.438] "remote.SSH.showLoginTerminal": false
[13:49:30.438] "remote.SSH.defaultExtensions": []
[13:49:30.438] "remote.SSH.loglevel": 2
[13:49:30.438] "remote.SSH.enableDynamicForwarding": true
[13:49:30.438] "remote.SSH.enableRemoteCommand": false
[13:49:30.438] "remote.SSH.serverPickPortsFromRange": {}
[13:49:30.438] "remote.SSH.serverInstallPath": {}
[13:49:30.443] SSH Resolver called for host: 1b9ada82-8da0-4f32-bf7c-52fdee8c6198
[13:49:30.443] Setting up SSH remote "1b9ada82-8da0-4f32-bf7c-52fdee8c6198"
[13:49:30.447] Using commit id "da76f93349a72022ca4670c1b84860304616aaa2" and quality "stable" for server
[13:49:30.449] Install and start server if needed
[13:49:34.383] PATH: /usr/local/sbin:/usr/local/bin:/Users/hexu/miniforge3/bin:/Users/hexu/miniforge3/condabin:/opt/local/bin:/opt/local/sbin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/Library/Apple/usr/bin
[13:49:34.383] Checking ssh with "ssh -V"
[13:49:34.392] > OpenSSH_8.6p1, LibreSSL 3.3.6

[13:49:34.394] Running script with connection command: ssh -T -D 59052 -o ConnectTimeout=15 '1b9ada82-8da0-4f32-bf7c-52fdee8c6198' bash
[13:49:34.607] > zsh:1: no such file or directory: /opt/conda/bin/python3
> kex_exchange_identification: Connection closed by remote host
> Connection closed by UNKNOWN port 65535
[13:49:34.607] Got some output, clearing connection timeout
[13:49:34.859] "install" terminal command done
[13:49:34.860] Install terminal quit with output: Connection closed by UNKNOWN port 65535
[13:49:34.860] Received install output: Connection closed by UNKNOWN port 65535
[13:49:34.862] Failed to parse remote port from server output
[13:49:34.863] Resolver error: Error: 
	at Function.Create (/Users/hexu/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:585222)
	at Object.t.handleInstallOutput (/Users/hexu/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:583874)
	at Object.t.tryInstall (/Users/hexu/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:681023)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async /Users/hexu/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:643908
	at async Object.t.withShowDetailsEvent (/Users/hexu/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:647224)
	at async Object.t.resolve (/Users/hexu/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:644958)
	at async /Users/hexu/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:727082
[13:49:34.870] ------

[13:49:34.926] ------

[13:49:34.926] SSH Resolver called for "ssh-remote+1b9ada82-8da0-4f32-bf7c-52fdee8c6198", attempt 2, (Reconnection)
[13:49:34.928] SSH Resolver called for host: 1b9ada82-8da0-4f32-bf7c-52fdee8c6198
[13:49:34.929] Setting up SSH remote "1b9ada82-8da0-4f32-bf7c-52fdee8c6198"
[13:49:34.929] Using commit id "da76f93349a72022ca4670c1b84860304616aaa2" and quality "stable" for server
[13:49:34.930] Install and start server if needed
[13:49:42.538] getPlatformForHost was canceled
[13:49:42.538] Resolver error: Error: Connecting was canceled
	at Function.Canceled (/Users/hexu/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:585418)
	at /Users/hexu/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:643820
	at async Object.t.withShowDetailsEvent (/Users/hexu/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:647224)
	at async Object.t.resolve (/Users/hexu/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:644958)
	at async /Users/hexu/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:727082
[13:49:42.542] ------

[13:49:42.547] ------

[13:49:42.547] SSH Resolver called for "ssh-remote+1b9ada82-8da0-4f32-bf7c-52fdee8c6198", attempt 3, (Reconnection)
[13:49:42.548] SSH Resolver called for host: 1b9ada82-8da0-4f32-bf7c-52fdee8c6198
[13:49:42.548] Setting up SSH remote "1b9ada82-8da0-4f32-bf7c-52fdee8c6198"
[13:49:42.549] Using commit id "da76f93349a72022ca4670c1b84860304616aaa2" and quality "stable" for server
[13:49:42.553] Install and start server if needed

### Environment

- Device or hardware: [e.g. iPhone6, Nvidia A100]

**Comment by ioga** [comment]
hello, 
1. have you managed to make it work since the last time you had the issue in #3857?
2. This error in the log looks suspicious:
> [13:49:34.607] > zsh:1: no such file or directory: /opt/conda/bin/python3
