### ISSUE TITLE
🐛[bug] show_ssh_command error on Windows CMD: module 'os' has no attribute 'uname'

### ISSUE THREAD

**Issue by agarcia-ruiz** [determined-ai/determined#8621]
### Describe the bug

Hi, I just updated determined from 0.26.4 to 0.26.7 on Windows (not WSL).
`show-ssh-command` or `show_ssh_command` now throw the following error:
```
C:\Users\...\Documents\GitHub\determine-config\shell_conda>det shell show-ssh-command faf506cb
Traceback (most recent call last):
  File "C:\Users\...\AppData\Roaming\Python\Python311\site-packages\determined\cli\cli.py", line 290, in main
    return func(namespace)
           ^^^^^^^^^^^^^^^
    return func(namespace)
           ^^^^^^^^^^^^^^^
  File "C:\Users\...\AppData\Roaming\Python\Python311\site-packages\determined\cli\shell.py", line 81, in show_ssh_command
    if "WSL" in os.uname().release:
                ^^^^^^^^
AttributeError: module 'os' has no attribute 'uname'
```
Was working before on 0.26.4. I found this recent addition (https://github.com/determined-ai/determined/pull/8387)

It seems `os.uname` is only available for some Unix systems.
As a quick check, it works if I use python `platform` module: `platform.uname()`

### Reproduction Steps

1. Start a determined shell (master node is remote Unix system in my case)
2. On Windows, run det shell show-ssh-command shell-id

### Expected Behavior

The command should work as before and output the ssh call string

### Screenshot

N/A

### Environment

- OS: Windows 10
- Determined 0.26.7

**Comment by ighodgao** [comment]
Hi! 

I currently use Windows and the best recommendation I have is to use WSL - we only have support for WSL as per our [docs](https://docs.determined.ai/latest/setup-cluster/on-prem/options/wsl.html#install-using-wsl). 

Please go through those install instructions, and let me know if you run into any issues.

**Comment by agarcia-ruiz** [comment]
Oh, my apologies, I thought it was supported. Closing the issue.
Will give WSL another go, since I tried before and had this problem with VS Code https://github.com/determined-ai/determined/issues/7726 , but I see there is a workaround posted now.

Best wishes for the new year!

**Comment by rb-determined-ai** [comment]
No... this is a bug.  The VS Code integration is supposed to work with determined installed outside of WSL.  cc @MikhailKardash.

This won't get fixed until the new year though.

**Comment by ighodgao** [comment]
My bad, thanks @rb-determined-ai!

**Comment by rb-determined-ai** [comment]
ok @agarcia-ruiz this should be fixed in the newest release, 0.27.0, which just landed.
